on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: PanVimDoc
        uses: ./
        with:
          markdown: README.md
          vimdoc: doc/panvimdoc.txt
