name: panvimdoc

on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Pandoc Markdown to Vim Markdown
    steps:
      - uses: actions/checkout@v2
      - name: PanVimDoc
        uses: ./
        with:
          pandoc: doc/panvimdoc.md
          vimdoc: doc/panvimdoc.txt
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto generate docs"
          branch: ${{ github.head_ref }}
