name: panvimdoc

on: [push, pull_request]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: ./
        with:
          vimdoc: panvimdoc
          pandoc: doc/panvimdoc.md
          description: pandoc markdown to vimdoc
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto generate docs"
          branch: ${{ github.head_ref }}
